name: ✨ Feature Request
description: Suggest a new feature or improvement for the app
title: "[Feature] <What should be added?>"
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
      placeholder: "What would you like to see added or improved?"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature useful?
      placeholder: "Explain the problem this solves or how it improves the experience."
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional context or examples
      placeholder: "Any mockups, links, or references?"
