name: 🚀 Suggest a New GitHub Tool
description: Propose a new GitHub-related tool to be added to the curated list
title: "[New Tool Request] <Tool Name>"
labels: [new-tool-request]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: "e.g., github1s"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      placeholder: e.g., GitHub1s
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: Homepage
      placeholder: "https://github1s.com"
    validations:
      required: true

  - type: input
    id: url-pattern
    attributes:
      label: URL pattern
      placeholder: "https://github1s.com/{owner}/{repo}"
    validations:
      required: true

  - type: input
    id: icon-url
    attributes:
      label: Icon URL
      placeholder: "https://github1s.com/favicon.ico"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "One second to read GitHub code with VS Code."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Development Tools
        - Analytics & Insights
        - Widgets & UI
        - Other
    validations:
      required: true

  - type: checkbox
    id: iframe
    attributes:
      label: Should this open inside an iframe?
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: "Any extra context?"
