name: 🚀 Suggest a New GitHub Tool
description: Propose a new GitHub-related tool to be added to the curated list
title: "[New Tool Request] <Tool Name>"
labels: [new-tool-request]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Short identifier for the tool (lowercase, no spaces)
      placeholder: "e.g., github1s"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: Display name for the tool
      placeholder: "e.g., GitHub1s"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of what the tool does
      placeholder: "One second to read GitHub code with VS Code."
    validations:
      required: true


  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: Main website URL for the tool
    validations:
  - type: input
    id: url
    attributes:
      label: URL Pattern
      description: URL template with {owner} and {repo} placeholders
      placeholder: "https://github1s.com/{owner}/{repo}"
    validations:
      required: true

  - type: input
    id: icon-url
    attributes:
      label: Icon URL
      description: Direct link to the tool's icon/favicon
      placeholder: "https://github1s.com/favicon.ico"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the most appropriate category
      options:
        - Development Tools
        - Code Visualization & Diagrams
        - Documentation & AI-Powered Understanding
        - Analytics & Insights
        - Widgets & UI
    validations:
      required: true

  - type: checkboxes
    id: iframe
    attributes:
      label: iFrame Support
      description: Can this tool be embedded in an iframe?
      options:
        - label: This tool supports iframe embedding

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any extra context or information
      placeholder: "Any extra context?"
      value: "_No additional notes_"
