# Keep Supabase databases alive by performing regular insert/delete cycles.
# Reference: https://github.com/travisvn/supabase-inactive-fix
#
# Required table:
# CREATE TABLE "keep-alive" (
#   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
#   name TEXT NULL DEFAULT '',
#   random UUID NULL DEFAULT gen_random_uuid(),
#   CONSTRAINT "keep-alive_pkey" PRIMARY KEY (id)
# );

import os
import sys
import logging
import secrets
import string
import random
from supabase import create_client, Client

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)


# -----------------------
# GitHub Actions helpers
# -----------------------
def gh_error(message: str) -> None:
    print(f"::error::{message}")


def gh_warning(message: str) -> None:
    print(f"::warning::{message}")


def gh_notice(message: str) -> None:
    print(f"::notice::{message}")


def write_github_outputs(status: str, failed_dbs: list[str], paused_dbs: list[str]) -> None:
    path = os.getenv("GITHUB_OUTPUT")
    if not path:
        return
    with open(path, "a") as f:
        f.write(f"status={status}\n")
        f.write(f"failed_dbs={','.join(failed_dbs) if failed_dbs else ''}\n")
        f.write(f"paused_dbs={','.join(paused_dbs) if paused_dbs else ''}\n")


def write_github_summary(
    status: str,
    failed_dbs: list[str],
    paused_dbs: list[str],
    report: list[dict],
) -> None:
    path = os.getenv("GITHUB_STEP_SUMMARY")
    if not path:
        return

    icon = "✅" if status == "success" else "❌"
    lines = [f"## {icon} Supabase Keep-Alive\n\n"]

    if status == "success":
        lines.append("All databases pinged successfully.\n\n")
    else:
        if paused_dbs:
            lines.append("### 🔴 Paused Databases\n\n")
            for db in paused_dbs:
                lines.append(f"- `{db}` — project is paused; resume it in the Supabase dashboard\n")
            lines.append("\n")

        failed_non_paused = [d for d in failed_dbs if d not in paused_dbs]
        if failed_non_paused:
            lines.append("### 🟡 Other Failures\n\n")
            for db in failed_non_paused:
                lines.append(f"- `{db}`\n")
            lines.append("\n")

    if report:
        lines.append("### Status Report\n\n")
        lines.append("| Database | Insert | Count | Delete |\n")
        lines.append("|---|---|---|---|\n")
        for s in report:
            delete_col = str(s["success_delete"]) if s["success_delete"] is not None else "N/A"
            lines.append(
                f"| {s['name']} | {s['success_insert']} | {s['count']} | {delete_col} |\n"
            )

    with open(path, "a") as f:
        f.writelines(lines)


# -----------------------
# Error classification
# -----------------------
def is_paused_error(e: Exception) -> bool:
    msg = str(e).lower()
    return "paused" in msg or "503" in msg or "service unavailable" in msg


# -----------------------
# Supabase client
# -----------------------
def generate_random_string(length: int) -> str:
    chars = string.ascii_letters + string.digits
    return "".join(secrets.choice(chars) for _ in range(length))


class SupabaseClient:
    def __init__(self, url: str, key: str, table_name: str) -> None:
        if not url or not key:
            raise ValueError("Supabase URL and Key must be provided.")
        self.client: Client = create_client(url, key)
        self.table_name = table_name

    def insert_random_name(self, name: str) -> bool:
        try:
            response = self.client.table(self.table_name).insert({"name": name}).execute()
            logging.info(f"Inserted into '{self.table_name}': {response.data}")
            return True
        except Exception as e:
            if is_paused_error(e):
                raise
            logging.error(f"Insert failed for '{self.table_name}': {e}")
            return False

    def get_table_count(self) -> int | None:
        try:
            response = self.client.table(self.table_name).select("*", count="exact").execute()
            return response.count
        except Exception as e:
            if is_paused_error(e):
                raise
            logging.error(f"Count failed for '{self.table_name}': {e}")
            return None

    def delete_random_entry(self) -> bool:
        try:
            response = self.client.table(self.table_name).select("id").execute()
            if not response.data:
                logging.info(f"No entries to delete in '{self.table_name}'.")
                return True
            random_id = random.choice([row["id"] for row in response.data])
            self.client.table(self.table_name).delete().eq("id", random_id).execute()
            logging.info(f"Deleted id={random_id} from '{self.table_name}'.")
            return True
        except Exception as e:
            if is_paused_error(e):
                raise
            logging.error(f"Delete failed for '{self.table_name}': {e}")
            return False


# -----------------------
# Main
# -----------------------
def main() -> None:
    configs = [
        {
            "name": os.getenv("SUPABASE_DB_NAME", "Database 1"),
            "supabase_url": os.getenv("SUPABASE_URL", ""),
            "supabase_key": os.getenv("SUPABASE_KEY", ""),
            "table_name": "keep-alive",
        }
    ]

    all_successful = True
    failed_dbs: list[str] = []
    paused_dbs: list[str] = []
    status_report: list[dict] = []

    for config in configs:
        name = config.get("name", "Unnamed Database")
        url = config.get("supabase_url", "")
        key = config.get("supabase_key") or os.getenv(config.get("supabase_key_env", ""), "")
        table_name = config.get("table_name", "keep-alive")

        if not url or not key:
            gh_error(f"[{name}] SUPABASE_URL or SUPABASE_KEY is missing — check your secrets.")
            logging.error(f"Missing credentials for '{name}'. Skipping.")
            all_successful = False
            failed_dbs.append(name)
            continue

        logging.info(f"Processing database: {name}")
        db = SupabaseClient(url, key, table_name)
        success_insert = False
        success_delete = None
        count = None

        try:
            success_insert = db.insert_random_name(generate_random_string(10))
            if not success_insert:
                raise RuntimeError("Insert returned False")

            count = db.get_table_count()
            if count is None:
                raise RuntimeError("Could not retrieve row count")

            logging.info(f"Row count in '{table_name}': {count}")

            if count > 10:
                logging.info(f"Over 10 rows — deleting a random entry.")
                success_delete = db.delete_random_entry()
                if not success_delete:
                    raise RuntimeError("Delete returned False")

        except Exception as e:
            all_successful = False
            if is_paused_error(e):
                paused_dbs.append(name)
                failed_dbs.append(name)
                gh_error(
                    f"[{name}] Supabase project is PAUSED. "
                    "Resume it at https://supabase.com/dashboard."
                )
                logging.error(f"Database '{name}' is paused: {e}")
            else:
                failed_dbs.append(name)
                gh_error(f"[{name}] Keep-alive failed: {e}")
                logging.error(f"Database '{name}' failed: {e}")
            continue

        status_report.append(
            {
                "name": name,
                "success_insert": success_insert,
                "success_delete": success_delete,
                "count": count,
            }
        )

    status = "success" if all_successful else "failure"

    if all_successful:
        gh_notice("All Supabase keep-alive pings succeeded.")
        logging.info("All database actions were successful.")
    else:
        logging.warning(f"Failed databases: {', '.join(failed_dbs)}")
        if paused_dbs:
            logging.warning(f"Paused databases: {', '.join(paused_dbs)}")

    write_github_outputs(status, failed_dbs, paused_dbs)
    write_github_summary(status, failed_dbs, paused_dbs, status_report)

    if not all_successful:
        sys.exit(1)


if __name__ == "__main__":
    main()
