# This script is designed to keep Supabase databases alive by performing regular insertions and deletions of random data.
# Reference :- https://github.com/travisvn/supabase-inactive-fix

# Install Dependencies :- 
# pip install supabase

# Initialize Supabase Client with your URL and Key, and specify the table name to use for keep-alive operations.
# CREATE TABLE "keep-alive" (
#   id BIGINT generated BY DEFAULT AS IDENTITY,
#   name text NULL DEFAULT '':: text,
#   random uuid NULL DEFAULT gen_random_uuid (),
#   CONSTRAINT "keep-alive_pkey" PRIMARY key (id)
# );

# INSERT INTO
#   "keep-alive"(name)
# VALUES
#   ('placeholder'),
#   ('example');


import json
import os
import logging
import secrets
import string
from supabase import create_client, Client

# User-defined variables to toggle additional features
log_failed_databases = True  # Set to True to log failed databases
detailed_status_report = True  # Set to True to generate a detailed status report

# Configure logging with timestamp
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

def generate_secure_random_string(length):
    """
    Generates a cryptographically secure random string of specified length.

    Parameters:
    - length (int): The length of the random string to generate.

    Returns:
    - str: A secure random string of the specified length.
    """
    if not isinstance(length, int) or length <= 0:
        raise ValueError("Length must be a positive integer.")

    characters = string.ascii_letters + string.digits
    # characters += string.punctuation  # Uncomment to include special characters

    random_string = ''.join(secrets.choice(characters) for _ in range(length))
    return random_string

class SupabaseClient:
    def __init__(self, url, key, table_name):
        if not url or not key:
            raise ValueError("Supabase URL and Key must be provided.")

        self.client: Client = create_client(url, key)
        self.table_name = table_name

    def insert_random_name(self, random_name):
        data = {'name': random_name}
        try:
            response = self.client.table(self.table_name).insert(data).execute()
            print(f"Inserted data into '{self.table_name}': {response.data}")
            return True
        except Exception as e:
            print(f"Error inserting data into '{self.table_name}': {e}")
            return False

    def get_table_count(self):
        try:
            response = self.client.table(self.table_name).select('*', count='exact').execute()
            if response.count is not None:
                return response.count
            else:
                print(f"Could not retrieve count from '{self.table_name}'.")
                return None
        except Exception as e:
            print(f"Error counting data in '{self.table_name}': {e}")
            return None

    def delete_random_entry(self):
        try:
            # Fetch all IDs from the table
            response = self.client.table(self.table_name).select('id').execute()
            if response.data:
                ids = [item['id'] for item in response.data]
                if not ids:
                    print(f"No entries to delete in '{self.table_name}'.")
                    return True  # No deletion needed, but not an error

                # Randomly select one ID to delete
                import random
                random_id = random.choice(ids)

                # Delete the entry with the selected ID
                self.client.table(self.table_name).delete().eq('id', random_id).execute()
                print(f"Deleted entry with id {random_id} from '{self.table_name}'.")
                return True
            else:
                print(f"No data retrieved from '{self.table_name}'.")
                return False
        except Exception as e:
            print(f"Error deleting data from '{self.table_name}': {e}")
            return False



def main():
    configs = [
        {
            "name": os.getenv("SUPABASE_DB_NAME", "Database 1"),
            "supabase_url": os.getenv("SUPABASE_URL", "your-supabase-url"),
            "supabase_key": os.getenv("SUPABASE_KEY", "your-supabase-key"),
            "table_name": "keep-alive"
        }
    ]
    all_successful = True  # Flag to track overall success

    # Initialize lists for additional features
    failed_databases = [] if log_failed_databases else None
    status_report = [] if detailed_status_report else None

    # Iterate over each configuration
    for config in configs:
        name = config.get('name', 'Unnamed Database')
        url = config.get('supabase_url')
        key = config.get('supabase_key')
        table_name = config.get('table_name', 'KeepAlive')

        # If using environment variables for keys
        key_env_var = config.get('supabase_key_env')
        if key_env_var:
            key = os.getenv(key_env_var)

        if not url or not key:
            logging.error(f"Supabase URL or Key missing for '{name}'. Skipping.")
            all_successful = False
            if log_failed_databases:
                if failed_databases is not None:
                    failed_databases.append(name)
            continue

        logging.info(f"Processing database: {name}")

        # Initialize Supabase client for this configuration
        supabase_client = SupabaseClient(url, key, table_name)

        # Generate a random string
        random_name = generate_secure_random_string(10)

        # Insert the random name into the table
        success_insert = supabase_client.insert_random_name(random_name)
        if not success_insert:
            all_successful = False
            if log_failed_databases and failed_databases is not None:
                failed_databases.append(name)
            # Proceed to next database since insertion failed
            continue

        # Get the count of entries in the table
        count = supabase_client.get_table_count()
        if count is None:
            logging.error(f"Failed to get count for table '{table_name}' in database '{name}'.")
            all_successful = False
            if log_failed_databases and failed_databases is not None:
                failed_databases.append(name)
            continue  # Skip to next configuration

        logging.info(f"Current number of entries in '{table_name}': {count}")

        # Initialize success_delete to None
        success_delete = None

        # If there are more than 10 entries, delete a random one
        if count > 10:
            logging.info(f"Table '{table_name}' has more than 10 entries. Deleting a random entry.")
            success_delete = supabase_client.delete_random_entry()
            if not success_delete:
                all_successful = False
                if log_failed_databases and failed_databases is not None and name not in failed_databases:
                    failed_databases.append(name)
        else:
            logging.info(f"Table '{table_name}' has 10 or fewer entries. No deletion needed.")

        # Collect status information
        if detailed_status_report:
            status = {
                'name': name,
                'success_insert': success_insert,
                'success_delete': success_delete,
                'count': count
            }
            if status_report is not None:
                status_report.append(status)

    # After processing all configurations
    if all_successful:
        logging.info("All database actions were successful.")
    else:
        logging.warning("Some database actions failed.")

        if log_failed_databases and failed_databases:
            logging.warning("Failed databases:")
            for db_name in failed_databases:
                logging.warning(f"- {db_name}")

    if detailed_status_report and status_report:
        logging.info("\nDetailed Status Report:")
        for status in status_report:
            logging.info(f"Database: {status['name']}")
            logging.info(f"  Insert Success: {status['success_insert']}")
            logging.info(f"  Entry Count: {status['count']}")
            if status['success_delete'] is not None:
                logging.info(f"  Delete Success: {status['success_delete']}")
            else:
                logging.info("  Delete Success: N/A")


if __name__ == "__main__":
    main()
